# Generated by Django 4.0.4 on 2022-06-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_police_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='police',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='abc', max_length=50)),
                ('l_name', models.CharField(default='efg', max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('designiation', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('c_password', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('s_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='polices', to='accounts.police_station')),
            ],
        ),
    ]
